# Generated by Django 4.2.5 on 2023-12-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_products_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.posts'),
        ),
    ]
