# Generated by Django 4.2.5 on 2023-12-23 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_products_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.posts'),
        ),
    ]
