# Generated by Django 4.2.5 on 2023-12-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_products_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='post',
        ),
    ]
