# Generated by Django 4.2.5 on 2023-12-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_products_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='ulike_post',
            field=models.ManyToManyField(null=True, related_name='liked_posts', to='project.user'),
        ),
    ]
