# Generated by Django 4.2.5 on 2024-01-20 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_posts_ulike_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='post_date',
        ),
        migrations.AddField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='products',
            name='contact_facebook',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='contact_line',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
