# Generated by Django 4.2.5 on 2024-01-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_products_post_date_posts_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='ulike_post',
            field=models.ManyToManyField(related_name='liked_posts', to='project.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
