# Generated by Django 4.2.5 on 2024-01-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_posts_ulike_post_alter_posts_user_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
