# Generated by Django 5.0.1 on 2024-01-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_delete_login_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(default='title_product', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='project.posts'),
        ),
    ]
