# Generated by Django 5.0.1 on 2024-01-24 14:54

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_userposts_delete_postproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_thumbnail',
            field=models.ImageField(null=True, upload_to=project.models.upload_to, verbose_name='Image'),
        ),
    ]
