# Generated by Django 5.0.1 on 2024-01-24 17:02

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_alter_posts_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(default=project.models.formatted_date),
        ),
        migrations.AlterField(
            model_name='products',
            name='img_src',
            field=models.ImageField(null=True, upload_to=project.models.upload_to, verbose_name='Image'),
        ),
    ]
