# Generated by Django 5.0.1 on 2024-01-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_userposts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='status',
            field=models.SmallIntegerField(choices=[(0, False), (1, True)], default=0),
        ),
    ]
