# Generated by Django 5.0.1 on 2024-01-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_alter_userposts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='status',
        ),
        migrations.AddField(
            model_name='userposts',
            name='status_like',
            field=models.SmallIntegerField(choices=[(0, False), (1, True)], default=1),
        ),
    ]
